version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    #allows docker to automatically update the image during developmnt
    develop:
      watch:
        - path: /app/
          target: /app/
          action: sync

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: