export const SUBTITLES = [
    "We missed you.",
    "Welcome back!",
    "Good to see you again.",
    "Long time no see.",
    "Back for more?",
    "Ready to dive back in?",
    "We're glad you're here.",
    "Amaze, Amaze, Amaze!",
    "We're no strangers to love.",
    "You know the rules, and so do I.",
    "A full commitment's what I'm thinking of.",
    "You wouldn't get this from any other guy.",
    "I just wanna tell you how I'm feeling.",
    "Gotta make you understand.",
    "Never gonna give you up.",
    "Never gonna let you down.",
    "Never gonna run around and desert you.",
    "Never gonna make you cry.",
    "Never gonna say goodbye.",
    "Never gonna tell a lie and hurt you.",
    "Everybody loves you!",
    "You better log back in, or else.",
    "Steal their hearts.",
    "Garlic bread.",
    "Groovy.",
    "September 30th, 1998.",
    "May the force be with you.",
    "Why so serious?",
    "You've grown!",
    "Welcome back, stranger.",
    "It's good to have you here.",
    "Domain Expansion!",
    "Delicious pancakes.",
    "You're on thin ice.",
    "Just beat it.",
    "Don't stop believin'.",
    "Get over here.",
    "Mamma mia.",
    "Everything is awesome.",
    "Very nice.",
    "The legend is here.",
    "The one and only.",
    "World ADOmination!!!",
    "Say wallahi bro.",
    "My mom is kinda homeless.",
    "*insert funny joke*",
    "You have entered the matrix.",
    "Protocol 3: Protect the Pilot.",
    "This is the part where you log in.",
    "Create memories.",
    "The adventure continues.",
    "Fun, fun, fun.",
    "I'm a punkrocker, yes I am!",
    "I don't like sand.",
    "Everybody lies.",
    "It's never lupus.",
    "Identity theft is not a joke!",
    "We are Charlie Kirk!",
    "We carry the flame.",
    "We'll fight for the gospel.",
    "We'll honor his name.",
    "His courage, our own.",
    "Hermit Purple!",
    "Chicken jockey!",
    "What da dog doin?",
    "Skibidi ohio gyatt.",
    "When the imposter is sus.",
    "I made a steak.",
    "Are you sure?",
    "Let's carve a path.",
    "For those who come after.",
    "When one falls, we continue.",
    "Tomorrow comes.",
    "Don't stop 'til you get enough.",
    "It's going down now.",
    "Play the game.",
    "Play Balatro today.",
    "Lisan al-Gaib.",
    "Low cortisol.",
    "Hashire, Hashire, Umamusume!",
    "Say my name.",
    "You're goddamn right.",
    "Clearly, you don't own an air fryer.",
    "I am the one who knocks.",
    "The return of the king.",
    "I bet you look good on the dancefloor.",
    "Freaking out the neighborhood.",
    "Thank you, Chainsaw Man.",
    "Everybody wants to rule the world.",
    "うっせぇうっせぇうっせぇわ",
    "We'll carry on.",
    "Don't look back in anger.",
    "Sally can wait.",
    "Don't forget, I'm with you in the dark.",
    "It's been so long.",
    "Where are you now?",
    "I see a little silhouetto of a man.",
    "Galileo Figaro, magnifico!",
    "Umapyoi, umapyoi!",
    "Wake up, get up, get out there.",
    "Wake me up before you go, go.",
    "Wake me up when September ends",
    "Good day.",
    "Everyday is a good day."
]

export const randomSubtitles = (subtitles: string[] = SUBTITLES) => {
  return subtitles[Math.floor(Math.random() * subtitles.length)]
}